// Pure-veg restaurants in Ahmedabad that serve Jain (no onion, no garlic) food.
// Prices are approximate "for two". Always tell the waiter "Jain" when ordering.
// Photos are Creative Commons images from Wikimedia Commons (dish / venue photos).
// To use your own photos, replace any URL in `photos` (max 4).

const W = (path) => `https://thumb.wikimedia.org/wikipedia/commons/thumb/${path}`;

export const RESTAURANTS = [
  {
    id: "agashiye",
    name: "Agashiye",
    tagline: "Rooftop heritage thali at The House of MG",
    area: "Lal Darwaja (Old City)",
    address: "The House of MG, Opp. Sidi Saiyed Jali, Lal Darwaja, Ahmedabad 380001",
    mapsQuery: "Agashiye The House of MG Lal Darwaja Ahmedabad",
    cuisine: ["Gujarati Thali"],
    price: 2400,
    jain: "On request — whole thali can be made Jain",
    fullySattvic: false,
    vibe: "Candle-lit terrace, 1920s mansion",
    picks: ["Jain Gujarati thali", "Seasonal farsan", "Hand-churned ice cream", "Kadhi & khichdi"],
    photos: [
      W("1/19/Authentic_gujarati_thali.jpg/960px-Authentic_gujarati_thali.jpg"),
      W("8/86/Shrikhand.JPG/960px-Shrikhand.JPG"),
      W("c/c9/Undhiyo%2C_handvo%2C_roti_served_with_gajar_ka_halwa.jpg/960px-Undhiyo%2C_handvo%2C_roti_served_with_gajar_ka_halwa.jpg"),
    ],
  },
  {
    id: "vishalla",
    name: "Vishalla",
    tagline: "Village-style dinner under lanterns",
    area: "Vasna",
    address: "Opp. APMC Market, Vishala Circle, Vasna, Ahmedabad 380055",
    mapsQuery: "Vishalla Restaurant Vasna Ahmedabad",
    cuisine: ["Gujarati Thali"],
    price: 1400,
    jain: "Jain thali on prior request",
    fullySattvic: false,
    vibe: "Floor seating, leaf plates, folk music",
    picks: ["Kathiyawadi thali (Jain)", "Bajra rotla with ghee", "Chaas", "Sukhdi"],
    photos: [
      W("a/aa/Gujarati_Thali_at_Vishalla.jpg/960px-Gujarati_Thali_at_Vishalla.jpg"),
      W("0/0e/Vishalla_Art_Gallery.jpg/960px-Vishalla_Art_Gallery.jpg"),
      W("4/41/Vishalla_Art_Gallery_2.jpg/960px-Vishalla_Art_Gallery_2.jpg"),
    ],
  },
  {
    id: "gordhan-thal",
    name: "Gordhan Thal",
    tagline: "Royal unlimited thali, legendary service",
    area: "Bodakdev, SG Highway",
    address: "Ground Floor, Sapath Complex, SG Highway, Opp. Rajpath Club, Bodakdev, Ahmedabad 380052",
    mapsQuery: "Gordhan Thal Sapath Complex SG Highway Ahmedabad",
    cuisine: ["Gujarati Thali", "Rajasthani"],
    price: 1100,
    jain: "Separate Jain thali available",
    fullySattvic: false,
    vibe: "Bright, family-friendly, fast refills",
    picks: ["Jain unlimited thali", "Dal baati", "Jalebi", "Rotla-bhakhri"],
    photos: [
      W("b/b1/Gordhan_Thal.jpg/960px-Gordhan_Thal.jpg"),
      W("9/9f/Dhokla_2.jpg/960px-Dhokla_2.jpg"),
      W("f/f5/Jalebi_1.jpg/960px-Jalebi_1.jpg"),
    ],
  },
  {
    id: "rajwadu",
    name: "Rajwadu",
    tagline: "Open-air Rajasthani village by the lake",
    area: "Jivraj Park, Malav Talav",
    address: "Nr. Jivraj Tolnaka, Behind Ambaji Temple, Malav Talav, Jivraj Park, Ahmedabad 380051",
    mapsQuery: "Rajwadu Restaurant Malav Talav Jivraj Park Ahmedabad",
    cuisine: ["Gujarati Thali", "Rajasthani"],
    price: 1400,
    jain: "Jain thali available — mention at entry",
    fullySattvic: false,
    vibe: "Khatiya seating, puppet shows, courtyard",
    picks: ["Jain Rajasthani thali", "Dal baati churma", "Gatte (Jain)", "Malpua"],
    photos: [
      W("5/59/GKN_Rajasthani_Thali_DSC_0213.JPG/960px-GKN_Rajasthani_Thali_DSC_0213.JPG"),
      W("1/17/Dal_Baati.jpg/960px-Dal_Baati.jpg"),
      W("7/7b/Handvo_1.jpg/960px-Handvo_1.jpg"),
    ],
  },
  {
    id: "govindas",
    name: "Govinda's (ISKCON)",
    tagline: "100% no onion, no garlic — the whole menu",
    area: "Satellite, SG Highway",
    address: "ISKCON Temple Campus, SG Highway, Satellite, Ahmedabad 380015",
    mapsQuery: "Govindas Restaurant ISKCON Temple Satellite Ahmedabad",
    cuisine: ["North Indian", "Multi-cuisine"],
    price: 1000,
    jain: "Entire kitchen is onion & garlic free",
    fullySattvic: true,
    vibe: "Calm temple campus, buffet + à la carte",
    picks: ["Paneer butter masala", "Sattvic thali", "Dal makhani", "Temple sweets"],
    photos: [
      W("4/4f/ISKCON_temple%2C_Ahmedabad.jpg/960px-ISKCON_temple%2C_Ahmedabad.jpg"),
      W("6/6f/Paneer_Butter_Masala_2.jpg/960px-Paneer_Butter_Masala_2.jpg"),
      W("8/8b/North_Indian_Vegetarian_Thali-MB51.jpg/960px-North_Indian_Vegetarian_Thali-MB51.jpg"),
    ],
  },
  {
    id: "swati-snacks",
    name: "Swati Snacks",
    tagline: "Iconic Gujarati snacks, reinvented",
    area: "Law Garden",
    address: "13, Gandhi Baug Society, Panchavati Rd, Opp. Nirman Bhavan, Law Garden, Ellisbridge, Ahmedabad 380006",
    mapsQuery: "Swati Snacks Law Garden Ahmedabad",
    cuisine: ["Street Food", "Gujarati"],
    price: 900,
    jain: "Most dishes can be made Jain",
    fullySattvic: false,
    vibe: "Busy, quick, everyone shares plates",
    picks: ["Panki", "Handvo", "Satpadi roti + aamras", "Dahi puri (Jain)"],
    photos: [
      W("9/91/Handvo_Gujarati_Food.jpg/960px-Handvo_Gujarati_Food.jpg"),
      W("3/3f/Dahi_Puri_%28Indian_snack%29.jpg/960px-Dahi_Puri_%28Indian_snack%29.jpg"),
      W("3/3c/Law_Garden%2C_Ahmedabad%2C_Gujarat%2C_INDIA.jpg/960px-Law_Garden%2C_Ahmedabad%2C_Gujarat%2C_INDIA.jpg"),
    ],
  },
  {
    id: "toran",
    name: "Toran Dining Hall",
    tagline: "30+ years of classic unlimited thali",
    area: "Ashram Road",
    address: "Opp. Sales India, Ashram Road, Ahmedabad 380009",
    mapsQuery: "Toran Dining Hall Ashram Road Ahmedabad",
    cuisine: ["Gujarati Thali"],
    price: 700,
    jain: "Jain thali available",
    fullySattvic: false,
    vibe: "No-fuss, great value, quick service",
    picks: ["Jain unlimited thali", "Dal dhokli", "Two farsans", "Seasonal sweet"],
    photos: [
      W("8/84/Gujarati_Thali_1.jpg/960px-Gujarati_Thali_1.jpg"),
      W("4/4b/Dal_dhokli.JPG/960px-Dal_dhokli.JPG"),
      W("b/bc/Thepla_2.jpg/960px-Thepla_2.jpg"),
    ],
  },
  {
    id: "gopi",
    name: "Gopi Dining Hall",
    tagline: "Old-school favourite near Town Hall",
    area: "Ellisbridge",
    address: "Nr. V.S. Hospital, Ellisbridge, Ahmedabad 380006",
    mapsQuery: "Gopi Dining Hall Ellisbridge Ahmedabad",
    cuisine: ["Gujarati Thali"],
    price: 700,
    jain: "Jain thali available",
    fullySattvic: false,
    vibe: "Homely taste, loved by locals",
    picks: ["Jain Gujarati thali", "Kadhi-khichdi", "Puran poli", "Chaas"],
    photos: [
      W("4/40/Gujarati_Thali.jpg/960px-Gujarati_Thali.jpg"),
      W("c/c8/Vegetable_Khichdi_1.jpg/960px-Vegetable_Khichdi_1.jpg"),
      W("8/86/Shrikhand.JPG/960px-Shrikhand.JPG"),
    ],
  },
  {
    id: "sankalp",
    name: "Sankalp",
    tagline: "The original South Indian, since 1980",
    area: "Ashram Road, Navrangpura",
    address: "16, Ashram Rd, Nr. Dinesh Hall, Embassy Market, Navrangpura, Ahmedabad 380009",
    mapsQuery: "Sankalp Restaurant Ashram Road Dinesh Hall Ahmedabad",
    cuisine: ["South Indian"],
    price: 800,
    jain: "Jain dosas, sambar & chutney on request",
    fullySattvic: false,
    vibe: "AC dining, family crowd",
    picks: ["Jain masala dosa (raw-banana filling)", "Idli sambar", "Rava dosa", "Filter coffee"],
    photos: [
      W("2/2e/Masala_Dosa_in_Banana_Leaf_with_Chutney.jpg/960px-Masala_Dosa_in_Banana_Leaf_with_Chutney.jpg"),
      W("1/1d/Idli_Sambhar_with_Coconut_Chatni.jpg/960px-Idli_Sambhar_with_Coconut_Chatni.jpg"),
      W("a/a4/Masala_Dosa_and_Vada.jpg/960px-Masala_Dosa_and_Vada.jpg"),
    ],
  },
  {
    id: "honest",
    name: "Honest",
    tagline: "Ahmedabad's pav bhaji institution since 1975",
    area: "Prahlad Nagar, SG Highway",
    address: "Circle P Complex, SG Highway, Nr. AUDA Garden, Prahlad Nagar, Ahmedabad 380015",
    mapsQuery: "Honest Restaurant Circle P Prahlad Nagar Ahmedabad",
    cuisine: ["Street Food", "North Indian"],
    price: 700,
    jain: "Jain items marked “J” on the menu",
    fullySattvic: false,
    vibe: "Casual, buzzing, quick bites",
    picks: ["Jain pav bhaji (raw-banana)", "Jain pulao", "Chole bhature", "Masala chaas"],
    photos: [
      W("1/1a/Pav_bhaji.jpg/960px-Pav_bhaji.jpg"),
      W("3/34/Bhaji_pav_2.jpg/960px-Bhaji_pav_2.jpg"),
      W("a/aa/Chole_Bhature_1.jpg/960px-Chole_Bhature_1.jpg"),
    ],
  },
  {
    id: "green-house",
    name: "The Green House",
    tagline: "Courtyard café for chaat & Gujarati bites",
    area: "Lal Darwaja (Old City)",
    address: "The House of MG, Opp. Sidi Saiyed Jali, Lal Darwaja, Ahmedabad 380001",
    mapsQuery: "The Green House House of MG Lal Darwaja Ahmedabad",
    cuisine: ["Street Food", "Café"],
    price: 900,
    jain: "Jain versions of most snacks",
    fullySattvic: false,
    vibe: "Leafy courtyard, relaxed evening hangout",
    picks: ["Jain pani puri", "Khaman", "Handvo", "Kulfi"],
    photos: [
      W("b/b2/Khaman-surarti.jpg/960px-Khaman-surarti.jpg"),
      W("5/5c/Crispy_Pani_Puri.jpg/960px-Crispy_Pani_Puri.jpg"),
      W("d/de/Handavo3.jpg/960px-Handavo3.jpg"),
    ],
  },
  {
    id: "jassi",
    name: "Jassi De Parathe",
    tagline: "Stuffed parathas, Punjabi style",
    area: "CG Road, Parimal Garden",
    address: "7, Dev Complex, Nr. Parimal Garden, CG Road, Ahmedabad 380006",
    mapsQuery: "Jassi De Parathe Parimal Garden CG Road Ahmedabad",
    cuisine: ["North Indian"],
    price: 650,
    jain: "Jain parathas & sabzi on request",
    fullySattvic: false,
    vibe: "Casual, hearty, great for groups",
    picks: ["Jain paneer paratha", "Gobi paratha (Jain)", "Dal fry", "Lassi"],
    photos: [
      W("0/02/Paratha_Sabji_MA01.jpg/960px-Paratha_Sabji_MA01.jpg"),
      W("7/7e/Masala_thepla_with_Methi_kela.JPG/960px-Masala_thepla_with_Methi_kela.JPG"),
      W("5/5e/Chole_Bhature_2.jpg/960px-Chole_Bhature_2.jpg"),
    ],
  },
  {
    id: "tomatos",
    name: "Tomato's",
    tagline: "Retro diner — pizza, sizzlers, Punjabi",
    area: "CG Road",
    address: "Mardia Plaza, CG Road, Navrangpura, Ahmedabad 380006",
    mapsQuery: "Tomatos Restaurant Mardia Plaza CG Road Ahmedabad",
    cuisine: ["Multi-cuisine", "Continental"],
    price: 1400,
    jain: "Jain pizza, sizzlers & Punjabi on request",
    fullySattvic: false,
    vibe: "Fun 50s-diner décor, good for celebrations",
    picks: ["Jain margherita pizza", "Veg shashlik sizzler (Jain)", "Paneer tikka", "Mocktails"],
    photos: [
      W("d/de/Margherita_pizza_on_plate.jpg/960px-Margherita_pizza_on_plate.jpg"),
      W("b/b1/Shashlik_sizzler.jpg/960px-Shashlik_sizzler.jpg"),
      W("7/7e/Paneer_Butter_Masala_3.jpg/960px-Paneer_Butter_Masala_3.jpg"),
    ],
  },
];

export const CUISINES = ["All", "Gujarati Thali", "South Indian", "Street Food", "North Indian", "Rajasthani", "Multi-cuisine"];

export const mapsSearchUrl = (r) =>
  `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(r.mapsQuery)}`;
export const mapsDirectionsUrl = (r) =>
  `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(r.mapsQuery)}`;
export const mapsEmbedUrl = (r) =>
  `https://maps.google.com/maps?q=${encodeURIComponent(r.mapsQuery)}&z=15&output=embed`;
export const menuUrl = (r) =>
  `https://www.google.com/search?q=${encodeURIComponent(`${r.name} ${r.area} Ahmedabad menu`)}`;
